import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const formulaNeutral = localFont({
  src: [
    {
      path: "./fonts/formular-neutral-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/formular-neutral-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/formular-neutral-bold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-custom-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${formulaNeutral.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
